export const SET_ALL_APPOINTMENTS = "SET_ALL_APPOINTMENTS";
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const SELECT_APPOINTMENT = "SELECT_APPOINTMENT";
export const RESET_SELECTED_APPOINTMENT = "RESET_SELECTED_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
