export const SET_PATIENT_TOOTH_DESCRIPTION = "SET_PATIENT_TOOTH_DESCRIPTION";
export const ADD_TOOTH_DESCRIPTION = "ADD_TOOTH_DESCRIPTION";
export const DELETE_TOOTH_DESCRIPTION = "DELETE_TOOTH_DESCRIPTION";
export const UPDATE_TOOTH_DESCRIPTION = "UPDATE_TOOTH_DESCRIPTION";